### ISSUE TITLE
Cannot find libsteaam_api.so

### ISSUE THREAD

**Issue by blindsighter314** [uspgamedev/luasteam#10]
Whenever I attempt to require luasteam.so I get the following error.

```
Error

error loading module 'luasteam' from file './luasteam.so':
libsteam_api.so: cannot open shared object file: No such file or directory

Traceback

[C]: at 0x7f86e885f310
[C]: in function 'require'
main.lua:2: in main chunk
[C]: in function 'require'
[C]: in function 'xpcall'
[C]: in function 'xpcall'
```

My OS is Ubuntu Linux 64 bit.
In my current configuration I have luasteam.so and libsteam_api.so sitting in the root game folder with main.lua.

I am requiring luasteam with

`steam = require 'luasteam'`

I have tried the pre compiled luasteam as well as compiling it myself with Lua 5.1 .h files. I have tried putting libsteam_api in the root folder as well as the save folder and the normal sdk folder, all with the same error.

I am using the latest release  of the Steamworks SDK as of November 11th. Any tips?

Thank you,

**Comment by yancouto** [comment]
Not sure exactly how you're running this command.

It might help if you set LD_LIBRARY_PATH to the directory that has libsteam, so something like

```
LD_LIBRARY_PATH=. lua main.lua
```

Does that help?

**Comment by blindsighter314** [comment]
That worked, thank you very much for the support.
