### ISSUE TITLE
Getting / Setting Stats

### ISSUE THREAD

**Issue by Pebsie** [uspgamedev/luasteam#15]
Hello! First off this project has saved me and my team a phenomenal amount of time, so thank you for that.

I was wondering if there are plans to add [getting](https://partner.steamgames.com/doc/api/ISteamUserStats#GetStat) / [setting of stats](https://partner.steamgames.com/doc/api/ISteamUserStats#SetStat)?

**Comment by yancouto** [comment]
Hello! I'm glad that this is being helpful to someone else :)

There are no plans to work further here for the time being, it was originally created to support our game, but it has been released for a while and we aren't in need of any other features from the Steam API.

That said, I made this repo and project so it was easy enough to contribute. Take a look at [CONTRIBUTING.md](https://github.com/uspgamedev/luasteam/blob/master/CONTRIBUTING.md), and feel free to submit PRs with changes! (See #12 for an example.)

ps. Would you be willing to share which project is using this? I think it would be nice to add some "Games that use luasteam" to the project README. 😄

**Comment by Pebsie** [comment]
Ah, that's a shame! I fear I lack the C++ knowledge to give it a good go, but when I have the time I'll try :)

My game is an MMORPG called BrawlQuest! Currently in early access :D 
https://store.steampowered.com/app/871940/BrawlQuest/

**Comment by yancouto** [comment]
Awesome! I'm closing the issue, feel free to submit any PRs when you're comfortable.
