### ISSUE TITLE
Add "games using luasteam" session on README

### ISSUE THREAD

**Issue by yancouto** [uspgamedev/luasteam#16]
That would be super nice to have.

Stuff to add:
- Marvellous Inc., of course
- [BrawlQuest](https://store.steampowered.com/app/871940/BrawlQuest/)
- @blindsighter314 @andrascsibi @oniietzschan you opened issues on this repo. Are the games you used luasteam for released? Would you be ok with sharing it so we can add it to our game list? Thanks :)

**Comment by andrascsibi** [comment]
Sure man, thanks for asking. [Terraforming Earth](https://store.steampowered.com/app/1029220/Terraforming_Earth/) is made with Love2d and luasteam. Luasteam worked great for me!

**Comment by oniietzschan** [comment]
Sure, feel free to add: https://store.steampowered.com/app/1040490/Prologue_for_a_Vacant_Kingdom/

**Comment by dxgldotorg** [comment]
Ocean's Heart - https://store.steampowered.com/app/1393750/Oceans_Heart/

**Comment by a327ex** [comment]
SNKRX - https://store.steampowered.com/app/915310/SNKRX/

**Comment by Elandig** [comment]
Works great. https://store.steampowered.com/app/743920/ChooChoo_The_Train_Rides/

**Comment by pakeke-constructor** [comment]
Thanks for making this library!
PushOps - https://store.steampowered.com/app/1705610/PushOps/

**Comment by GreenVerdeDude** [comment]
Thank you for making this library, it helped us a lot!
Heliotropism - https://store.steampowered.com/app/1653100/Heliotropism/

**Comment by teamttlcic** [comment]
Thank you!
Skoory Rush - https://store.steampowered.com/app/2399810/Skoory_Rush/

**Comment by ApexNAM** [comment]
It was a great help to work on Steamworks in love2d. thank you!
Roots Need Control 3.0 - https://store.steampowered.com/app/2425570/Roots_Need_Control_30/

**Comment by rfht** [comment]
not my own game, but Gravity Circuit uses luasteam: https://store.steampowered.com/app/858710/Gravity_Circuit/

**Comment by abhimonk** [comment]
I really appreciated this API, thanks for making it.
My game Putrid Shot Ultra uses luasteam: https://store.steampowered.com/app/2053360/PUTRID_SHOT_ULTRA/

**Comment by Introvertigo** [comment]
I appreciate you making this!

Our crime-themed 4X strategy game, called ALL IN THE GAME uses Luasteam

**Comment by vaughantay** [comment]
Seconding/thirding/fourthing all the thanks for making this.
Possession uses Luasteam: https://store.steampowered.com/app/629340/Possession/

**Comment by phansWind** [comment]
Kanji Drive = https://store.steampowered.com/app/2219640/Kanji_Drive/

Are we able to get global stats with luasteam? Thank you.

**Comment by Saturn91** [comment]
Hello ;)

Descent from arkovs Tower Prologue (and later full version)

https://store.steampowered.com/app/2688600/Descent_from_Arkovs_tower_Prologue/

**Comment by rilifon** [comment]
Added all past games mentioned here. If I missed one, please let me know :)

**Comment by tmesser** [comment]
https://store.steampowered.com/app/2290890/Endless_Dark/ Endless Dark now uses Luasteam!

**Comment by RuairiD** [comment]
[Bang Average Football](https://store.steampowered.com/app/2393770/Bang_Average_Football/), thanks for all your help! ☺️

**Comment by Brunobap** [comment]
[Paratroopers Raid](https://store.steampowered.com/app/3127690/Paratroopers_Raid/). You guys really helped with this bind. Thank you.

**Comment by NextOp-Next** [comment]
[Chaperon Inc.](https://store.steampowered.com/app/3093090/Chaperon_Inc/) uses luasteam. Really useful!

**Comment by kingziox** [comment]
[Trivia War](https://store.steampowered.com/app/3472880/Trivia_War/) Uses luasteam! Thank you so much for this module.
