### ISSUE TITLE
Steam network api

### ISSUE THREAD

**Issue by Ismoh** [uspgamedev/luasteam#26]
I had a look on your documentation and wasnt able to see network functions.

Does your wrapper provide steam network api stuff like https://github.com/ValveSoftware/GameNetworkingSockets ( https://partner.steamgames.com/doc/features/multiplayer/networking ) ?

If I would be able to use C++, I would create a PR, but I never worked with C++

**Comment by yancouto** [comment]
No, we do not have those functions currently. I don't plan on working on those personally, but we accept PRs.

**Comment by Ismoh** [comment]
Yea, if you can somehow provide an example, I am interested in creating a PR, but I am not fimiliar with C++ that much.
Would be nice to have an example to get used to it.

**Comment by yancouto** [comment]
Take a look at [Contributing.md](https://github.com/uspgamedev/luasteam/blob/master/CONTRIBUTING.md) and the previously closed pull requests, there are a few examples of people adding new methods.

**Comment by pakeke-constructor** [comment]
Hi @Ismoh, I think we can use luaJIT's FFI to access the GameNetworkingSockets directly from lua.
If I have trouble with that, I might try adding the functionality directly to luasteam, (in which case i'll open a PR.)

**Comment by Ismoh** [comment]
Yea, I think so too, but I am really bad in lua, luaJIT FFI and C+. Still learning. Would be awesome, if you can give me a shout, after your research.
Thanks a lot!

**Comment by pakeke-constructor** [comment]
Unfortunetely, I don't think that GameNetworkingSockets have C bindings, which means they won't be accessible to luaJIT's FFI. :(

**Comment by pakeke-constructor** [comment]
Nevermind!!!
@Ismoh We're saved!! steam *does* have C bindings for their SDK.

Everything is defined in `steam_api_flat.h`:
https://github.com/Facepunch/Facepunch.Steamworks/blob/master/Generator/steam_sdk/steam_api_flat.h

**Comment by Ismoh** [comment]
Can you provide an example?
We may should dont missuse this issue, maybe?

**Comment by Ismoh** [comment]
> @Ismoh If you are still interested in it, I'm making [good progress](https://github.com/zorfmorf/luasteam/pull/1/files). I'm not planning to implement every single function and so far I'm only doing the Sockets API for a client/server architecture, so no NetworkingMessages or P2P functions, but if you need more, it should be easy to add and you're welcome to contribute.

Awesome!
I am currently pretty busy, but I am still interested in. Will get back to this for sure!

**Comment by pakeke-constructor** [comment]
Thanks a tonne for this!!!

**Comment by yancouto** [comment]
Closing as #27 is merged and soon will be released
