### ISSUE TITLE
Game invite functionality

### ISSUE THREAD

**Issue by Introvertigo** [uspgamedev/luasteam#29]
Hi there, would it be possible to add the _Invite To Game_ feature that can be used in the Friends overlay to invite a friend to a game? As far as I understood, there are three functions and one callback that would enable this in Luasteam.

**functions:**
ActivateGameOverlayInviteDialog (https://partner.steamgames.com/doc/api/ISteamFriends#ActivateGameOverlayInviteDialog)
InviteUserToGame
(https://partner.steamgames.com/doc/api/ISteamFriends#InviteUserToGame)
GetLaunchCommandLine
(https://partner.steamgames.com/doc/api/ISteamApps#GetLaunchCommandLine)

**callbacks:**
GameRichPresenceJoinRequested_t
(https://partner.steamgames.com/doc/api/ISteamFriends#GameRichPresenceJoinRequested_t)

**Comment by zorfmorf** [comment]
I will try to add it!
