### ISSUE TITLE
ISteamUser::GetAuthSessionTicket adds additional parameter

### ISSUE THREAD

**Issue by keharriso** [uspgamedev/luasteam#31]
`ISteamUser::GetAuthSessionTicket` now takes an extra parameter: `const SteamNetworkingIdentity *pIdentityRemote`.

"The identity of the remote system that will authenticate the ticket. If it is peer-to-peer then the user steam ID. If it is a game server, then the game server steam ID may be used if it was obtained from a trusted 3rd party, otherwise use the IP address. If it is a service, a string identifier of that service if one if provided."

```c++
HAuthTicket GetAuthSessionTicket( void *pTicket, int cbMaxTicket, uint32 *pcbTicket, const SteamNetworkingIdentity *pIdentityRemote  );
```

**Comment by hylje** [comment]
PR proposal here https://github.com/uspgamedev/luasteam/pull/32

**Comment by yancouto** [comment]
This was done. Thanks @hylje !
