### ISSUE TITLE
IPlayerService::GetOwnedGames

### ISSUE THREAD

**Issue by MichaelHinrichs** [uspgamedev/luasteam#35]
I want to be able to scan a users steam library.
https://developer.valvesoftware.com/wiki/Steam_Web_API#GetOwnedGames_.28v0001.29

**Comment by yancouto** [comment]
This is in the steam web api, which luasteam does not support. I didn't find any equivalent in the normal Steamworks API, though I might have missed it.

**Comment by yancouto** [comment]
I'm closing this as steam web api is not on the scope of luasteam
