### ISSUE TITLE
Segmentation fault when loading luasteam on x86 macOS, but not arm64

### ISSUE THREAD

**Issue by RuairiD** [uspgamedev/luasteam#44]
I've been able to use luasteam in a game without issue in Windows, Linux and arm64 macOS, but I'm having trouble with x86 macOS. I'm using Steamworks SDK version 1.53a as this was the first version where `libsteam_api.dylib` supported arm64, and I never bothered updating further during development, and luasteam version 1.2.0 as this was the latest version at the time when I added Steam integration to the game in question.

I've put together a minimal example with .so and .dylib files for x86 and arm64 macOS: [luasteam-x86-crash-minimal-example.zip](https://github.com/user-attachments/files/16325973/luasteam-x86-crash-minimal-example.zip). `osx_x86_luasteam.so` is taken directly from the 1.2.0 release and `osx_arm64_luasteam.so` was re-compiled for arm64.
The example copies the .so and .dylib files to the LÖVE save directory and loads them from there (I can't remember completely since this was more than a year ago, but loading .so files didn't seem to work of they were inside a .love file?). Running the example on both architectures (actual machines, no Rosetta involved) yields the following outputs:

arm64

```
$ love luasteam-x86-crash-minimal-example
love.system.getOS	OS X
jit.arch	arm64
Copying luasteam lib files to /Users/ruairi/Library/Application Support/LOVE/luasteam-x86-crash-minimal-example/copied-lib/
Copying file .DS_Store to copied-lib/.DS_Store...
Copying file libsteam_api.dylib to copied-lib/libsteam_api.dylib...
Copying file osx_arm64_luasteam.so to copied-lib/osx_arm64_luasteam.so...
Copying file osx_x86_luasteam.so to copied-lib/osx_x86_luasteam.so...
Loading luasteam lib from /Users/ruairi/Library/Application Support/LOVE/luasteam-x86-crash-minimal-example/copied-lib/osx_arm64_luasteam.so
Loaded luasteam lib successfully.
Attempting Steam.init()...
[S_API] SteamAPI_Init(): Loaded '/Users/ruairi/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/steamclient.dylib' OK.
Setting breakpad minidump AppID = 2393770
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198051111097 [API loaded no]
Steam.init() succeeded.
Steam.userStats.onUserStatsReceived() called.
```

x86

```
$ love luasteam-x86-crash-minimal-example
love.system.getOS	OS X
jit.arch	x64
Copying luasteam lib files to /Users/ruairi/Library/Application Support/LOVE/luasteam-x86-crash-minimal-example/copied-lib/
Copying file .DS_Store to copied-lib/.DS_Store...
Copying file libsteam_api.dylib to copied-lib/libsteam_api.dylib...
Copying file osx_arm64_luasteam.so to copied-lib/osx_arm64_luasteam.so...
Copying file osx_x86_luasteam.so to copied-lib/osx_x86_luasteam.so...
Loading luasteam lib from /Users/ruairi/Library/Application Support/LOVE/luasteam-x86-crash-minimal-example/copied-lib/osx_x86_luasteam.so
[1]    35802 segmentation fault  love.app/Contents/MacOS/love luasteam-x86-crash-minimal-example
```

If I remove the .dylib file, the example fails gracefully without crashing as the .so file can't find the .dylib file. Not sure if this is a useful clue since much of this is beyond my experience but chucking it in there just in case.

Thanks in advance, really appreciative of any suggestions or pointers!

**Comment by yancouto** [comment]
We recently changed how we build the library for OSX to make it universal, so I believe this should be fixed in 3.2.1. Feel free to reopen if it still doesn't work.

**Comment by RuairiD** [comment]
Hi @yancouto , thanks for the response! I upgraded luasteam to 3.2.1 and used SDK version 1.58a as recommended in the docs. This definitely got me further as the library can be loaded without segfaulting. However, I'm having a weird issue (again, only on x86, not arm64) where running `runCallbacks()` causes very weird LÖVE/Lua behaviour where built-in functions/tables like `print`, `type` and `love` seem to have their values changed. Here's another minimal example:

[luasteam-x86-crash-minimal-example-3.2.1.zip](https://github.com/user-attachments/files/16551533/luasteam-x86-crash-minimal-example-3.2.1.zip)

And the outputs for arm64 and x86:

arm64

```
love.system.getOS	OS X
jit.arch	arm64
Copying luasteam lib files to /Users/ruairi/Library/Application Support/LOVE/luasteam-x86-crash-minimal-example/copied-lib/
Copying file .DS_Store to copied-lib/.DS_Store...
Copying file libsteam_api.dylib to copied-lib/libsteam_api.dylib...
Copying file osx_luasteam.so to copied-lib/osx_luasteam.so...
Loading luasteam lib from /Users/ruairi/Library/Application Support/LOVE/luasteam-x86-crash-minimal-example/copied-lib/osx_luasteam.so
Loaded luasteam lib successfully.
Attempting Steam.init()...
[S_API] SteamAPI_Init(): Loaded '/Users/ruairi/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/steamclient.dylib' OK.
Setting breakpad minidump AppID = 2393770
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198051111097 [API loaded no]
Steam.init() succeeded.
2024-08-08 10:27:03.843 love[50676:10010969] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
Steam.userStats.onUserStatsReceived() called.
type	function: builtin#3
type(love)	table
```

x86

```
love.system.getOS	OS X
jit.arch	x64
Copying luasteam lib files to /Users/ruairi/Library/Application Support/LOVE/luasteam-x86-crash-minimal-example/copied-lib/
Copying file .DS_Store to copied-lib/.DS_Store...
Copying file libsteam_api.dylib to copied-lib/libsteam_api.dylib...
Copying file [osx_luasteam.so](http://osx_luasteam.so/) to copied-lib/osx_luasteam.so...
Loading luasteam lib from /Users/ruairi/Library/Application [Support/LOVE/luasteam-x86-crash-minimal-example/copied-lib/osx_luasteam.so](http://support/LOVE/luasteam-x86-crash-minimal-example/copied-lib/osx_luasteam.so)
Loaded luasteam lib successfully.
Attempting Steam.init()...
[S_API] SteamAPI_Init(): Loaded '/Users/ruairi/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/steamclient.dylib' OK.
Setting breakpad minidump AppID = 2393770
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198051111097 [API loaded no]
Steam.init() succeeded.
Error: main.lua:56: attempt to call global 'print' (a table value)
stack traceback:
	[love "boot.lua"]:345: in function 'print'
	main.lua:56: in function <main.lua:55>
	[C]: in function 'runCallbacks'
	main.lua:79: in function 'update'
	[love "callbacks.lua"]:162: in function <[love "callbacks.lua"]:144>
	[C]: in function 'xpcall'
Error: main.lua:82: attempt to call global 'print' (a table value)
stack traceback:
	[love "boot.lua"]:345: in function 'print'
	main.lua:82: in function 'update'
	[love "callbacks.lua"]:162: in function <[love "callbacks.lua"]:144>
	[C]: in function 'xpcall'
```

Any idea what might be going on? This isn't my area of expertise but [the library code looks very straightforward](https://github.com/uspgamedev/luasteam/blob/827a1adb4bf9f2770a0c1ac85054bac80c0e3aac/src/core.cpp#L55-L58) and I can't spot anything obvious that would be messing with lua state.

Thanks again!

**Comment by RuairiD** [comment]
@jamespanic 👋 mentioning you here since you worked on macOS cross-compatibility (https://github.com/uspgamedev/luasteam/pull/45, thank you!!), it's possible you have an idea what's going on.

**Comment by jamespanic** [comment]
@RuairiD  Are you able to repro this problem using 3.2.0 on x86? That version doesn't contain an arm version and uses an older version of the luajit. FWIW we're using this in a game that's about to ship and it's working fine on the mac.

**Comment by RuairiD** [comment]
Hi @jamespanic thanks for such a quick response! There's no pre-compiled binary for 3.2.0 so I compiled it myself, and it actually had the same segfault that I initially opened this issue for. My first thought was that I'd built the object incorrectly, but `objdump` also reports that the 3.1.0 precompiled binary is 'invalid/unsupported' (and it also segfaults the same way), while it seems happy with 3.2.1:

```
$ objdump -x steam/osx_luasteam_x86-3.1.0.so | head -n 10
/Library/Developer/CommandLineTools/usr/bin/objdump:
steam/osx_luasteam_x86-3.1.0.so:	file format mach-o 64-bit x86-64
error: 'steam/osx_luasteam_x86-3.1.0.so': Invalid/Unsupported object file format

$ objdump -x steam/osx_luasteam_x86-3.2.0.so | head -n 10
/Library/Developer/CommandLineTools/usr/bin/objdump:
steam/osx_luasteam_x86-3.2.0.so:	file format mach-o 64-bit x86-64
error: 'steam/osx_luasteam_x86-3.2.0.so': Invalid/Unsupported object file format

$ objdump -x steam/osx_luasteam_x86-3.2.1.so | head -n 10
steam/osx_luasteam_x86-3.2.1.so:

Sections:
Idx Name             Size     VMA              Type
  0 __text           000800d6 00000000000017e0 TEXT
  1 __stubs          0000040e 00000000000818b6 TEXT
  2 __gcc_except_tab 00000634 0000000000081cc4 DATA
  3 __const          00004278 0000000000082300 DATA
  4 __cstring        0000365b 0000000000086580 DATA
  5 __unwind_info    00001f20 0000000000089bdc DATA
error: write on a pipe with no reader
```

(head used for brevity, just illustrating that it read the file rather than showing anything specific in the dump)

Again, arm64 working fine for all of this.

Also is the game Arco? (guessing since it's a Panic + LÖVE collaboration)

**Comment by jamespanic** [comment]
I'm looking at your original example now and you absolutely can load libraries from inside the mac app bundle containing your .love game. The following code will load the .so from the Frameworks folder

```lua
STEAM = false
local LIB_SEARCH_PATH = love.filesystem.getSourceBaseDirectory()
if love.system.getOS() == "OS X" then
  LIB_SEARCH_PATH = LIB_SEARCH_PATH .. "/../Frameworks"
end
package.cpath = ("%s;%s/?.%s"):format(
  package.cpath,
  LIB_SEARCH_PATH,
  (
    love.system.getOS() == "Windows" and "dll"
    or "so"
  )
)
local result, message = pcall(function()
  STEAM = require("luasteam")
  if not STEAM or not STEAM.init() then
    STEAM = false
  end
end)
if not result or not STEAM then
  STEAM = false
end
print(STEAM and "connected steam" or "couldn't connect steam" .. message)
```

Unfortunately I can't really speak to the legitimacy of any older releases as I only started working with this repo recently. Are you able to run the latest version successfully?

**Comment by RuairiD** [comment]
Thanks for sharing your example and taking the time to look at mine. I hadn't considered putting the libraries in the Frameworks folder in the .app itself (never really done any macOS development!). The outcome was the same as before unfortunately, so it may not make a difference if the library is loaded from the save directory or the Frameworks folder.

However, I tried removing all the code in the `Steam.userStats.onUserStatsReceived()` callback, and that actually seemed to 'fix' it (not really fixed since I would like to use those callbacks if possible, but at least the app doesn't crash). It's almost like the callbacks aren't getting the correct lua/LÖVE state; references to anything outside the callback scope seem to fail, as do attempts to do arithmetic or anything useful. The app also segfaults when the game is exited (again, x86 only):

```
5702 segmentation fault  love-11.4-luasteam.app/Contents/MacOS/love
```

I've put together another minimal example using the Frameworks folder and `require()` to load the library as you described, and removed any problematic code from the callback. This example includes the source main.lua as well as a LÖVE 11.4 app with the .so and .dylib in the Frameworks folder.

[luasteam-x86-crash-minimal-example-using-frameworks-3.2.1.zip](https://github.com/user-attachments/files/16554552/luasteam-x86-crash-minimal-example-using-frameworks-3.2.1.zip)

Very strange! Really appreciate your help so far, interested to see if any of this sounds familiar at all.
